export interface AreaGuide {
  slug: string
  name: string
  province: string
  description: string
  longDescription: string
  latitude: number
  longitude: number
  population: string
  avgRent: string
  avgSale: string
  highlights: string[]
  amenities: { name: string; count?: string }[]
  transport: string[]
  safety: string
  bestFor: string[]
  images: string[]
  gradient: string
}

export const areaGuides: AreaGuide[] = [
  {
    slug: 'lusaka-central',
    name: 'Lusaka Central',
    province: 'Lusaka',
    description:
      'The vibrant heart of Zambia\'s capital city, where government buildings, shopping malls, and bustling streets create a dynamic urban atmosphere perfect for professionals and business owners.',
    longDescription:
      'Lusaka Central is the beating heart of Zambia\'s capital and its primary commercial district. Home to key government institutions, international corporate offices, and some of the city\'s most popular shopping destinations, this area pulses with energy from dawn to dusk. Cairo Road, the main thoroughfare, is lined with banks, retail shops, restaurants, and street vendors selling everything from fresh fruit to phone accessories. The district\'s central location makes it a hub for public transport, with minibus routes radiating outward to every corner of the city.\n\nLiving in Lusaka Central means having the city\'s best amenities at your doorstep. Arcades Shopping Mall and Manda Hill Mall offer world-class retail experiences with supermarkets, fashion boutiques, cinemas, and food courts. The area is well-served by healthcare facilities including University Teaching Hospital (UTH), the largest referral hospital in Zambia. For professionals working in government, finance, or international organisations, Lusaka Central offers unmatched convenience with short commutes and excellent connectivity. Property here commands premium prices, but the investment is justified by the area\'s proximity to essential services and its strong rental demand from expats and corporate tenants.',
    latitude: -15.3875,
    longitude: 28.3228,
    population: '~3.1 million (metro)',
    avgRent: 'K5,000 – K25,000/month',
    avgSale: 'K800,000 – K8,000,000',
    highlights: [
      'Government & diplomatic district',
      'Cairo Road — main commercial artery',
      'Arcades Shopping Mall',
      'Manda Hill Shopping Mall',
      'Levy Junction Mall nearby',
      'University Teaching Hospital (UTH)',
      'Lusaka International Airport (25 min drive)',
      'Vibrant street food & nightlife scene',
      'Central business district with major banks',
      'Annual Lusaka July Festival nearby',
    ],
    amenities: [
      { name: 'Levy Junction Mall', count: '120+ stores' },
      { name: 'Arcades Shopping Mall', count: '80+ stores' },
      { name: 'Manda Hill Mall', count: '95+ stores' },
      { name: 'University Teaching Hospital', count: '1,800+ beds' },
      { name: 'Lusaka International Airport', count: '25 min' },
      { name: 'International Schools', count: '15+' },
      { name: 'Banks & ATMs', count: '50+' },
      { name: 'Hotels & Guesthouses', count: '60+' },
      { name: 'Supermarkets', count: '20+' },
      { name: 'Restaurants & Cafes', count: '100+' },
      { name: 'Fitness Centres', count: '10+' },
      { name: 'Pharmacies', count: '30+' },
    ],
    transport: [
      'Minibus taxis on Cairo Road (routes to all suburbs)',
      'Uber and local ride-hailing apps (Yango, Bolt)',
      'Private taxis from designated ranks',
      'Kenneth Kaunda International Airport shuttle services',
      'Long-distance bus terminals to Copperbelt, Southern, Eastern provinces',
      'Walking-friendly central corridors',
    ],
    safety: 'Moderate — the central business district is generally safe during daytime with visible police presence. Night-time caution is advised in quieter side streets. Gated parking and security guards are standard in residential compounds. Expats and locals alike recommend using ride-hailing apps for evening travel.',
    bestFor: ['Professionals', 'Business owners', 'Expats', 'Young professionals', 'Government workers'],
    images: [],
    gradient: 'from-emerald-600 to-teal-700',
  },
  {
    slug: 'rhodes-park',
    name: 'Rhodes Park',
    province: 'Lusaka',
    description:
      'An upscale residential neighbourhood known for its quiet tree-lined streets, embassy residences, and proximity to the city centre — a favoured choice for diplomats, families, and senior professionals.',
    longDescription:
      'Rhodes Park is one of Lusaka\'s most sought-after residential areas, prized for its serene atmosphere and leafy, well-maintained streets. Located just minutes from the central business district, this neighbourhood offers the rare combination of tranquillity and urban convenience. Many foreign embassies and high commissions have their residences here, giving the area an international flavour and contributing to its reputation as one of the safest neighbourhoods in the capital. Properties in Rhodes Park range from charming older colonial-era homes to modern luxury residences, often set on generous plots with mature gardens.\n\nFamilies appreciate Rhodes Park for its proximity to top-tier schools, including Baobab College and the International School of Lusaka, both within easy reach. Shopping needs are well served by nearby Manda Hill Mall and Arcades, while healthcare is covered by several private clinics and the nearby UTH for specialist care. The area boasts reliable utilities compared to other parts of Lusaka, and many properties come with boreholes, solar panels, and backup generators. For anyone seeking a peaceful, secure base in Lusaka with quick access to the city\'s commercial and social amenities, Rhodes Park represents an excellent long-term investment.',
    latitude: -15.4086,
    longitude: 28.3128,
    population: '~12,000',
    avgRent: 'K8,000 – K35,000/month',
    avgSale: 'K1,500,000 – K12,000,000',
    highlights: [
      'Quiet tree-lined residential streets',
      'Embassy row — diplomatic residences',
      'Close to city centre (5–10 min drive)',
      'Proximity to Manda Hill & Arcades malls',
      'Well-maintained infrastructure & roads',
      'Strong community feel & neighbourhood watch',
      'Mature gardens & large property plots',
      'Reliable utilities & boreholes common',
      'Near top international schools',
      'Low crime rate with private security patrols',
    ],
    amenities: [
      { name: 'Manda Hill Mall', count: '10 min drive' },
      { name: 'Arcades Shopping Mall', count: '8 min drive' },
      { name: 'International School of Lusaka', count: '1 campus' },
      { name: 'Baobab College', count: '15 min drive' },
      { name: 'Lusaka Trust Hospital', count: '1 facility' },
      { name: 'Cure Hospital', count: '1 facility' },
      { name: 'Private Clinics', count: '8+' },
      { name: 'Supermarkets', count: '5+' },
      { name: 'Restaurants', count: '15+' },
      { name: 'Gyms & Sports Clubs', count: '4+' },
      { name: 'Parks & Green Spaces', count: '3+' },
      { name: 'Churches & Mosques', count: '6+' },
    ],
    transport: [
      'Minibus routes along Great East Road',
      'Ride-hailing apps (Uber, Bolt, Yango)',
      'Private taxis readily available',
      'Short drive to Cairo Road taxi rank',
      '15 min drive to Kenneth Kaunda International Airport',
      'Easy access to Great East Road highway',
    ],
    safety: 'High — Rhodes Park is considered one of the safest residential areas in Lusaka. The presence of diplomatic residences means enhanced security patrols, and most properties have 24-hour guards, electric fences, and alarm systems. Street crime is rare, and the neighbourhood watch is active and well-organised.',
    bestFor: ['Families', 'Diplomats', 'Senior professionals', 'Expats', 'Retirees'],
    images: [],
    gradient: 'from-green-700 to-emerald-800',
  },
  {
    slug: 'kabulonga',
    name: 'Kabulonga',
    province: 'Lusaka',
    description:
      'Lusaka\'s premier premium residential enclave, renowned for its expansive properties, gated communities, and concentration of diplomatic missions — the address of choice for Zambia\'s elite.',
    longDescription:
      'Kabulonga sits at the very top of Lusaka\'s real estate market, and for good reason. This exclusive neighbourhood in the south-east of the city is home to sprawling estates, luxury gated communities, and an impressive concentration of foreign embassies and high commissioners\' residences. Properties here are among the most expensive in Zambia, with stately homes set on plots of half an acre or more, often featuring swimming pools, manicured gardens, servants\' quarters, and state-of-the-art security systems. The wide, well-paved roads and abundant greenery give Kabulonga a distinctly suburban feel despite being only 20 minutes from the city centre.\n\nThe area caters exceptionally well to international families. The American International School of Lusaka (AISL) and the French School (Lycée Français) are both located within or near Kabulonga, making it the neighbourhood of choice for expatriate families with school-age children. Shopping is convenient with Levy Junction Mall and East Park Mall a short drive away. For recreation, residents enjoy access to nearby golf courses, sports clubs, and the Lusaka South Country Club. While property prices are significantly higher than the city average, Kabulonga properties tend to hold their value exceptionally well and offer strong rental yields, particularly for furnished homes let to diplomatic tenants and international organisations.',
    latitude: -15.4350,
    longitude: 28.3500,
    population: '~18,000',
    avgRent: 'K15,000 – K80,000/month',
    avgSale: 'K3,000,000 – K25,000,000',
    highlights: [
      'Lusaka\'s most exclusive residential area',
      'Embassy row — numerous diplomatic missions',
      'Large plots (0.5–2 acre properties)',
      'Gated communities with 24/7 security',
      'American International School (AISL) nearby',
      'French School (Lycée Français) in the area',
      'Levy Junction Mall — 10 min drive',
      'Wide, well-paved roads with minimal traffic',
      'Mature trees & lush landscaping',
      'Proximity to golf courses & country clubs',
      'Strong property value appreciation',
      'High demand for diplomatic rentals',
    ],
    amenities: [
      { name: 'Levy Junction Mall', count: '120+ stores, 10 min' },
      { name: 'East Park Mall', count: '60+ stores, 12 min' },
      { name: 'American International School', count: '1 campus' },
      { name: 'Lycée Français de Lusaka', count: '1 campus' },
      { name: 'Lusaka South Country Club', count: '1 facility' },
      { name: 'Private Hospitals & Clinics', count: '6+' },
      { name: 'Supermarkets (Shoprite, Pick n Pay)', count: '4+' },
      { name: 'Fine Dining Restaurants', count: '10+' },
      { name: 'Gyms & Wellness Centres', count: '5+' },
      { name: 'Salons & Spas', count: '8+' },
      { name: 'Boutiques & Specialty Stores', count: '12+' },
      { name: 'Pharmacies', count: '5+' },
    ],
    transport: [
      'Private vehicles recommended (limited public transit)',
      'Ride-hailing apps available but longer wait times',
      'Dedicated chauffeur services common for residents',
      '20 min drive to city centre / Cairo Road',
      '25 min drive to Kenneth Kaunda International Airport',
      'Easy access to Kafue Road and Great East Road',
    ],
    safety: 'Very High — Kabulonga is arguably the safest neighbourhood in Lusaka. Virtually all properties have comprehensive security packages including 24-hour armed guards, electric fencing, CCTV, alarm systems linked to rapid response units, and gated access control. The diplomatic presence adds an extra layer of security infrastructure. Street crime is extremely rare.',
    bestFor: ['High-income families', 'Expats', 'Diplomats', 'International executives', 'Retirees'],
    images: [],
    gradient: 'from-teal-700 to-cyan-800',
  },
  {
    slug: 'woodlands',
    name: 'Woodlands',
    province: 'Lusaka',
    description:
      'A well-planned, popular middle-class neighbourhood offering a balanced lifestyle with good schools, convenient shopping, and a strong sense of community — ideal for families and young professionals.',
    longDescription:
      'Woodlands is one of Lusaka\'s most beloved middle-class neighbourhoods, consistently ranking among the top choices for families and young professionals looking for a balanced urban lifestyle. Located in the southern part of the city, Woodlands is a well-planned area with a grid-like street layout, reliable water and electricity supply (by Lusaka standards), and a real sense of community spirit. The neighbourhood is divided into sections (Woodlands Phase I and II), each with its own character but sharing the same family-friendly atmosphere. Housing stock ranges from modest three-bedroom homes to larger modern residences, making it accessible to a wide range of budgets.\n\nWhat makes Woodlands particularly attractive is its self-contained convenience. The area has its own shopping centres, including the popular Woodlands Shopping Centre with a Spar supermarket, pharmacies, bakeries, and casual dining options. Several well-regarded schools are within walking or short driving distance, including Woodlands School and St. Mary\'s Academy. Healthcare is well-covered with Woodlands Clinic and several private practices. The neighbourhood also benefits from its proximity to Levy Junction Mall and the Great East Road commercial corridor. For property buyers or renters seeking a safe, family-oriented community without the premium price tag of Kabulonga or Rhodes Park, Woodlands offers excellent value for money with strong rental demand and steady property appreciation.',
    latitude: -15.4200,
    longitude: 28.2900,
    population: '~25,000',
    avgRent: 'K3,500 – K15,000/month',
    avgSale: 'K600,000 – K3,500,000',
    highlights: [
      'Well-planned grid layout with wide streets',
      'Strong middle-class community atmosphere',
      'Woodlands Shopping Centre & local amenities',
      'Good selection of primary & secondary schools',
      'Reliable utilities compared to other areas',
      'Proximity to Levy Mall (10 min drive)',
      'Family-friendly with parks and green spaces',
      'Good rental yields for investors',
      'Affordable entry point for first-time buyers',
      'Active neighbourhood association',
      'Easy access to Great East Road',
      'Range of property types & price points',
    ],
    amenities: [
      { name: 'Woodlands Shopping Centre', count: '20+ stores' },
      { name: 'Levy Junction Mall', count: '10 min drive' },
      { name: 'Woodlands School', count: 'Primary & Secondary' },
      { name: 'St. Mary\'s Academy', count: '1 campus' },
      { name: 'Woodlands Clinic', count: '1 facility' },
      { name: 'Private Medical Practices', count: '10+' },
      { name: 'Spar Supermarket', count: '1 store' },
      { name: 'Local Markets & Butchers', count: '8+' },
      { name: 'Restaurants & Takeaways', count: '15+' },
      { name: 'Churches', count: '10+' },
      { name: 'Sports Fields & Playgrounds', count: '5+' },
      { name: 'Salons & Barber Shops', count: '10+' },
    ],
    transport: [
      'Minibus routes along Great East Road & Kafue Road',
      'Ride-hailing apps (Uber, Bolt, Yango)',
      'Local taxis from Woodlands shopping area',
      '15 min drive to city centre',
      '25 min drive to Kenneth Kaunda International Airport',
      'Easy access to Kafue Road (south) and Great East Road (east)',
    ],
    safety: 'Good — Woodlands is considered a safe, family-friendly neighbourhood. Most properties have wall fencing, burglar bars, and night security guards. The neighbourhood watch is active, and crime rates are lower than the city average. As with any urban area in Lusaka, basic precautions are recommended, but residents generally feel safe walking during daytime and early evening hours.',
    bestFor: ['Families', 'Young professionals', 'First-time buyers', 'Investors', 'Retirees'],
    images: [],
    gradient: 'from-green-600 to-lime-700',
  },
  {
    slug: 'kitwe',
    name: 'Kitwe',
    province: 'Copperbelt',
    description:
      'Zambia\'s second-largest city and the commercial heart of the Copperbelt, built on a foundation of copper mining but now a diversified economic hub with thriving markets, modern malls, and a growing services sector.',
    longDescription:
      'Kitwe is the second-largest city in Zambia and the undisputed commercial capital of the Copperbelt Province. Founded in the 1930s as a copper mining town, Kitwe has grown into a vibrant, diverse city that serves as the economic engine of northern Zambia. While copper mining remains central to the local economy — with major operations like Mopani Copper Mines and Konkola Copper Mines nearby — the city has successfully diversified into manufacturing, retail, banking, and services. Kitwe\'s Chisokone Market is one of the largest open-air markets in Zambia, where thousands of traders sell everything from fresh produce and second-hand clothing to electronics and building materials.\n\nFor property seekers, Kitwe offers significantly more affordable options than Lusaka while still providing a good quality of life. The city boasts modern shopping centres like Kitwe Mall and Mukuba Mall, several hospitals and clinics, and a range of educational institutions including Kitwe\'s Copperbelt University campus. Residential areas like Parklands, Riverside, and Nkana East offer leafy, well-established neighbourhoods with good infrastructure. The city\'s road network connects easily to Ndola (45 min), Chingola (30 min), and Chililabombwe (1 hour), making it an ideal base for mining professionals who need to commute to various mine sites. Kitwe\'s property market has shown consistent growth, driven by ongoing mining investment and the city\'s expanding middle class.',
    latitude: -12.8024,
    longitude: 28.2093,
    population: '~717,000 (city)',
    avgRent: 'K2,000 – K12,000/month',
    avgSale: 'K250,000 – K3,000,000',
    highlights: [
      'Zambia\'s second-largest city',
      'Commercial heart of the Copperbelt',
      'Chisokone Market — one of Zambia\'s largest',
      'Kitwe Mall — modern shopping centre',
      'Mukuba Mall — retail & entertainment hub',
      'Copperbelt University campus',
      'Gateway to copper mining operations',
      'Strong manufacturing sector',
      'Nkana Golf Club — 18-hole course',
      'Diverse dining & nightlife scene',
      '45 min drive to Ndola International Airport',
      'Growing middle class driving property demand',
    ],
    amenities: [
      { name: 'Kitwe Mall', count: '40+ stores' },
      { name: 'Mukuba Mall', count: '35+ stores' },
      { name: 'Chisokone Market', count: '5,000+ traders' },
      { name: 'Kitwe Central Hospital', count: '1 facility' },
      { name: 'Wusakile Hospital', count: '1 facility' },
      { name: 'Copperbelt University', count: '1 campus' },
      { name: 'Private Schools', count: '10+' },
      { name: 'Banks & Financial Services', count: '15+' },
      { name: 'Supermarkets (Shoprite, Pick n Pay)', count: '5+' },
      { name: 'Hotels & Lodges', count: '20+' },
      { name: 'Restaurants & Bars', count: '40+' },
      { name: 'Fitness Centres', count: '5+' },
    ],
    transport: [
      'Extensive minibus network (routes to all Copperbelt towns)',
      'Inter-city buses to Lusaka (5–6 hrs), Ndola (45 min)',
      'Railway connection via Zambia Railways',
      'Taxi services from designated ranks',
      '45 min drive to Simon Mwansa Kapwepwe International Airport (Ndola)',
      'Private hire and ride-hailing emerging',
    ],
    safety: 'Moderate — Kitwe is generally safe during daylight hours, especially in residential areas like Parklands and Nkana East. The city centre and market areas can be busy and require standard urban precautions. Residential properties typically have security fences and guards. Mine-related areas have additional security measures. Night travel in unfamiliar areas is not recommended.',
    bestFor: ['Mining professionals', 'Traders', 'Business owners', 'Families', 'Investors'],
    images: [],
    gradient: 'from-amber-600 to-orange-700',
  },
  {
    slug: 'ndola',
    name: 'Ndola',
    province: 'Copperbelt',
    description:
      'The provincial capital of the Copperbelt and a key business gateway, Ndola combines industrial strength with modern amenities, an international airport, and a growing property market attractive to business travellers and investors.',
    longDescription:
      'Ndola is the capital of Zambia\'s Copperbelt Province and the third-largest city in the country. As the administrative centre of Zambia\'s wealthiest province, Ndola plays a crucial role in the national economy, serving as a major hub for trade, manufacturing, and transportation. The city is home to Simon Mwansa Kapwepwe International Airport, which provides direct connections to Lusaka, Johannesburg, and Nairobi, making it an important entry point for international business travellers and investors. Ndola\'s economy has historically been tied to copper mining and processing, but the city has developed a diverse industrial base including textiles, food processing, pharmaceuticals, and cement manufacturing.\n\nProperty in Ndola offers excellent value compared to Lusaka, with a wide range of options from affordable housing in areas like Chifubu and Twashuka to premium residences in Itawa and Northrise. The city\'s infrastructure has seen significant investment in recent years, including road upgrades, new shopping centres (Savoy Mall, and several newly developed plazas), and improved water and power supply. Ndola is also home to the impressive Levy Mwanawasa Stadium, a 45,000-seat multi-purpose venue that hosts international football matches and cultural events. For property investors, Ndola presents a compelling opportunity: lower entry prices than Lusaka, strong rental demand from corporate and mining-sector tenants, and the potential for significant capital appreciation as the city continues to grow and attract investment.',
    latitude: -12.9586,
    longitude: 28.6366,
    population: '~510,000 (city)',
    avgRent: 'K2,500 – K15,000/month',
    avgSale: 'K300,000 – K4,000,000',
    highlights: [
      'Provincial capital of Copperbelt Province',
      'Simon Mwansa Kapwepwe International Airport',
      'Levy Mwanawasa Stadium (45,000 seats)',
      'Diverse industrial & manufacturing base',
      'Savoy Hotel — historic landmark',
      'Growing modern retail sector',
      'Direct flights to Lusaka, Johannesburg, Nairobi',
      'Strong mining sector employment',
      'Quality residential areas (Itawa, Northrise)',
      'Ndola Golf Club — established 18-hole course',
      'Regional trade hub for DRC & Tanzania corridors',
      'Expanding middle class & housing demand',
    ],
    amenities: [
      { name: 'Savoy Mall', count: '30+ stores' },
      { name: 'Ndola International Airport', count: 'Domestic & Regional' },
      { name: 'Levy Mwanawasa Stadium', count: '45,000 capacity' },
      { name: 'Ndola Central Hospital', count: '1 facility' },
      { name: 'TdH Children\'s Hospital', count: '1 facility' },
      { name: 'Copperbelt University (main campus nearby)', count: '15 min drive' },
      { name: 'Private Schools', count: '12+' },
      { name: 'Ndola Golf Club', count: '1 facility' },
      { name: 'Banks & Financial Institutions', count: '15+' },
      { name: 'Supermarkets', count: '6+' },
      { name: 'Hotels & Conference Centres', count: '15+' },
      { name: 'Industrial Parks & SEZs', count: '3+' },
    ],
    transport: [
      'Minibus network connecting all city suburbs',
      'Inter-city buses to Lusaka (4.5 hrs), Kitwe (45 min), Kabwe (2 hrs)',
      'Simon Mwansa Kapwepwe International Airport (domestic & regional flights)',
      'Railway line to Kitwe, Lusaka, and Livingstone',
      'Taxis from airport, city centre, and bus stations',
      'Good road connections to DRC border (Kasumbalesa) and Tanzania (Tunduma)',
    ],
    safety: 'Moderate — Ndola is a generally safe city with a visible police presence in commercial areas. Residential neighbourhoods like Itawa, Northrise, and Kansenshi are considered safe with standard home security measures. The city centre and industrial areas are busy during the day but quieter at night. Night travel should be done with caution, and ride-hailing or private transport is recommended after dark.',
    bestFor: ['Business travellers', 'Mining professionals', 'Investors', 'Families', 'Government workers'],
    images: [],
    gradient: 'from-yellow-600 to-amber-700',
  },
  {
    slug: 'livingstone',
    name: 'Livingstone',
    province: 'Southern',
    description:
      'Zambia\'s tourism capital, gateway to the magnificent Victoria Falls and Mosi-oa-Tunya National Park — a city of natural wonder, adventure tourism, and growing investment appeal for lifestyle buyers.',
    longDescription:
      'Livingstone is Zambia\'s crown jewel of tourism, a charming city perched on the northern bank of the Zambezi River, directly opposite the world-famous Victoria Falls — known locally as Mosi-oa-Tunya (The Smoke That Thunders). Named after the legendary explorer David Livingstone, the city has a rich colonial heritage reflected in its historic buildings and tree-lined avenues. Livingstone is the base from which millions of visitors each year experience one of the Seven Natural Wonders of the World, and the tourism industry has shaped every aspect of the city\'s character and economy. Adventure activities abound: bungee jumping from the Victoria Falls Bridge, white-water rafting on the Zambezi, microlight flights over the falls, sunset river cruises, and game drives in Mosi-oa-Tunya National Park, where you can spot white rhinos, giraffes, elephants, and zebras.\n\nFor property buyers, Livingstone presents a unique proposition. The city\'s property market is more affordable than Lusaka\'s, but it benefits from a steady stream of tourism-related investment and a growing number of retirees and lifestyle buyers drawn by the city\'s natural beauty and relaxed pace of life. Residential areas like Maramba and Libuyu offer affordable family homes, while areas closer to the Zambezi River and the Falls attract premium prices for holiday homes, boutique lodges, and guesthouses. The city has good basic infrastructure, including the Harry Mwaanga Nkumbula International Airport with direct flights from Lusaka, Johannesburg, and Nairobi. Livingstone is also home to the Zambia National Museum, the Livingstone Museum, and several art galleries. With tourism numbers projected to grow significantly in the coming years, property in Livingstone represents both a lifestyle choice and a sound investment opportunity.',
    latitude: -17.8419,
    longitude: 25.8536,
    population: '~180,000',
    avgRent: 'K2,000 – K12,000/month',
    avgSale: 'K200,000 – K3,500,000',
    highlights: [
      'Gateway to Victoria Falls (Mosi-oa-Tunya)',
      'Mosi-oa-Tunya National Park — rhinos, elephants, giraffes',
      'Adventure capital of Zambia (bungee, rafting, microlight)',
      'Harry Mwaanga Nkumbula International Airport',
      'Livingstone Museum — national history & culture',
      'Sunset Zambezi River cruises',
      'Historic colonial architecture & charm',
      'Growing eco-tourism & sustainable travel sector',
      'Royal Livingstone Hotel — luxury riverside resort',
      'Annual Livingstone Arts & Cultural Festival',
      'Proximity to Kazungula Border (Botswana, Namibia, Zimbabwe)',
      'Strong short-term rental demand from tourists',
    ],
    amenities: [
      { name: 'Harry Mwaanga Nkumbula Airport', count: 'Regional flights' },
      { name: 'Mosi-oa-Tunya National Park', count: '1 major park' },
      { name: 'Livingstone Museum', count: '1 facility' },
      { name: 'Livingstone General Hospital', count: '1 facility' },
      { name: 'Private Clinics', count: '5+' },
      { name: 'Schools (primary & secondary)', count: '15+' },
      { name: 'Supermarkets', count: '4+' },
      { name: 'Hotels, Lodges & Guesthouses', count: '50+' },
      { name: 'Adventure Activity Operators', count: '20+' },
      { name: 'Restaurants & Bars', count: '25+' },
      { name: 'Craft Markets', count: '3+' },
      { name: 'Banks & ATMs', count: '8+' },
    ],
    transport: [
      'Harry Mwaanga Nkumbula International Airport (flights from Lusaka, JNB, NBO)',
      'Minibus and taxi services within the city',
      'Inter-city buses to Lusaka (6 hrs) and Sesheke (3 hrs)',
      'Kazungula Ferry to Botswana (1 hr)',
      'Victoria Falls Bridge crossing to Zimbabwe (15 min)',
      'Tour shuttle services to Falls & national park',
    ],
    safety: 'Good — Livingstone is one of Zambia\'s safer cities, thanks partly to the importance of tourism to the local economy. The tourist areas around the Falls and along the Zambezi are well-patrolled and generally very safe. Residential areas are quiet and community-oriented. Standard precautions should be taken, but visitors and residents alike typically report feeling safe. The city has a relaxed, welcoming atmosphere.',
    bestFor: ['Tourism businesses', 'Retirees', 'Nature lovers', 'Adventure enthusiasts', 'Investors', 'Lifestyle buyers'],
    images: [],
    gradient: 'from-sky-600 to-blue-700',
  },
  {
    slug: 'kabwe',
    name: 'Kabwe',
    province: 'Central',
    description:
      'A historic mining town and provincial capital of Central Province, Kabwe offers budget-friendly property options and is emerging as an investment opportunity with improving infrastructure and strategic location on the Great North Road.',
    longDescription:
      'Kabwe is the capital of Zambia\'s Central Province and one of the country\'s oldest towns, with a rich mining heritage that dates back to the early 1900s when it was known as Broken Hill — the site of one of the world\'s first and richest lead and zinc mines. While mining activity has significantly reduced since the mine\'s closure in the 1990s, Kabwe\'s strategic location on the Great North Road, roughly halfway between Lusaka and the Copperbelt, has ensured its continued importance as a commercial and administrative centre. The town is perhaps best known historically as the place where the Broken Hill Man skull was discovered in 1921 — one of the most important hominid fossils ever found, now housed in the Livingstone Museum.\n\nFor property buyers and investors, Kabwe represents one of Zambia\'s most affordable markets. Property prices are a fraction of those in Lusaka, Ndola, or Kitwe, making it an attractive option for first-time buyers, budget-conscious families, and speculative investors betting on the town\'s growth potential. The town\'s infrastructure has seen gradual improvement, including road rehabilitation, new shopping developments, and improved water supply. Key residential areas include Kabwe East, Riverside, and Lukanga, which offer a range of housing options from modest starter homes to larger family residences. Kabwe is also home to Mulungushi University of Science and Technology, which brings a student population and associated rental demand. The town\'s proximity to both Lusaka (2 hours south) and the Copperbelt (2 hours north) makes it a viable commuter base, and the government\'s focus on decentralising economic activity to provincial capitals is expected to drive future growth.',
    latitude: -14.4469,
    longitude: 28.3939,
    population: '~220,000',
    avgRent: 'K800 – K5,000/month',
    avgSale: 'K80,000 – K800,000',
    highlights: [
      'Provincial capital of Central Province',
      'Rich mining heritage (Broken Hill mine)',
      'Strategic location on Great North Road',
      'Halfway between Lusaka & Copperbelt (~2 hrs each)',
      'Mulungushi Rock of Authority — historic site',
      'Mulungushi University of Science & Technology',
      'Highly affordable property market',
      'Growing commercial & retail sector',
      'Kabwe River & surrounding natural beauty',
      'Improving road infrastructure',
      'Student rental market from university',
      'Government decentralisation driving investment',
    ],
    amenities: [
      { name: 'Kabwe General Hospital', count: '1 facility' },
      { name: 'Mulungushi University', count: '1 campus' },
      { name: 'Kabwe Central Market', count: '1,000+ traders' },
      { name: 'Private Clinics', count: '8+' },
      { name: 'Primary & Secondary Schools', count: '25+' },
      { name: 'Banks & Financial Services', count: '6+' },
      { name: 'Supermarkets', count: '3+' },
      { name: 'Filling Stations', count: '5+' },
      { name: 'Hotels & Guesthouses', count: '8+' },
      { name: 'Restaurants', count: '12+' },
      { name: 'Churches & Mosques', count: '15+' },
      { name: 'Government Offices', count: 'Provincial HQ' },
    ],
    transport: [
      'Great North Road — primary highway (Lusaka to Copperbelt)',
      'Minibus and taxi services to Lusaka (2 hrs) and Ndola (2 hrs)',
      'Railway line (Tazara) connecting to Kapiri Mposhi, Lusaka, and Tanzania',
      'Inter-city bus services (Mazhandu Family Bus, etc.)',
      'Local minibus routes within the town',
      '45 min drive to Kapiri Mposhi (Tazara railway terminus)',
    ],
    safety: 'Moderate — Kabwe has a mixed safety profile. The town centre is busy during the day with a visible police presence. Residential areas vary, with newer suburbs like Kabwe East generally safer than older neighbourhoods. Properties typically have wall fencing and burglar bars. Some areas require extra caution at night. The town is generally safe for visitors during daytime, but local advice should be sought when choosing residential areas.',
    bestFor: ['Budget-conscious buyers', 'Investors', 'First-time buyers', 'Students & academics', 'Commuters to Lusaka/Copperbelt'],
    images: [],
    gradient: 'from-stone-600 to-zinc-700',
  },
]

export function getGuideBySlug(slug: string): AreaGuide | undefined {
  return areaGuides.find((g) => g.slug === slug)
}

export function getProvinces(): string[] {
  return [...new Set(areaGuides.map((g) => g.province))]
}
