import { PrismaClient } from '@prisma/client'

const db = new PrismaClient()

const lodges = [
  {
    id: 'lodge-riverside-lusaka',
    name: 'Riverside Lodge Lusaka',
    description: 'A modern lodge nestled along the banks of the Kafue River, offering serene views, a sparkling pool, and easy access to Lusaka city centre. Perfect for business travellers and tourists alike. Each room features air conditioning, free WiFi, and a private bathroom. Enjoy our on-site restaurant serving local and international cuisine.',
    location: 'Lusaka',
    address: '12 Cairo Road, Lusaka, Zambia',
    phone: '+260 977 123 456',
    price: 450,
    priceUnit: 'night',
    latitude: -15.3875,
    longitude: 28.3228,
    images: JSON.stringify(['/lodges/riverside-lodge-lusaka.jpg']),
    amenities: JSON.stringify(['WiFi', 'Pool', 'Breakfast', 'Parking', 'AC', 'Restaurant', 'Bar']),
    rating: 4.7,
    totalRooms: 12,
  },
  {
    id: 'lodge-victoria-falls-retreat',
    name: 'Victoria Falls Retreat',
    description: 'Experience luxury just minutes from the mighty Victoria Falls. Our retreat offers breathtaking views, world-class dining, and guided tour services. Wake up to the sound of rushing water and unwind by our infinity pool overlooking the Zambezi gorge.',
    location: 'Livingstone',
    address: '8 Mosi-oa-Tunya Road, Livingstone, Zambia',
    phone: '+260 966 234 567',
    price: 780,
    priceUnit: 'night',
    latitude: -17.8488,
    longitude: 25.8542,
    images: JSON.stringify(['/lodges/victoria-falls-retreat.jpg']),
    amenities: JSON.stringify(['WiFi', 'Pool', 'Breakfast', 'Parking', 'AC', 'Restaurant', 'Bar']),
    rating: 4.9,
    totalRooms: 10,
  },
  {
    id: 'lodge-copperbelt-suites-kitwe',
    name: 'Copperbelt Suites Kitwe',
    description: 'Modern business accommodation in the heart of the Copperbelt. Fully equipped rooms with workspace, high-speed internet, and 24-hour front desk. Ideal for corporate guests visiting the mining and industrial hub of Kitwe.',
    location: 'Kitwe',
    address: '45 Independence Avenue, Kitwe, Zambia',
    phone: '+260 955 345 678',
    price: 350,
    priceUnit: 'night',
    latitude: -12.8026,
    longitude: 28.2134,
    images: JSON.stringify(['/lodges/copperbelt-suites.jpg']),
    amenities: JSON.stringify(['WiFi', 'Breakfast', 'Parking', 'AC', 'Restaurant']),
    rating: 4.3,
    totalRooms: 15,
  },
  {
    id: 'lodge-ndola-garden-hotel',
    name: 'Ndola Garden Hotel',
    description: 'A peaceful garden hotel set amid lush tropical greenery in Ndola. Our spacious rooms open onto private patios overlooking beautiful gardens. Enjoy complimentary breakfast, an outdoor pool, and warm Zambian hospitality.',
    location: 'Ndola',
    address: '23 Bwana Mkubwa Road, Ndola, Zambia',
    phone: '+260 977 456 789',
    price: 400,
    priceUnit: 'night',
    latitude: -12.9588,
    longitude: 28.6364,
    images: JSON.stringify(['/lodges/ndola-garden-hotel.jpg']),
    amenities: JSON.stringify(['WiFi', 'Pool', 'Breakfast', 'Parking', 'AC', 'Restaurant', 'Bar']),
    rating: 4.5,
    totalRooms: 10,
  },
  {
    id: 'lodge-lake-kariba-inn',
    name: 'Lake Kariba Inn Siavonga',
    description: 'Stunning lakeside lodge on the shores of Lake Kariba. Watch spectacular sunsets from your private balcony, enjoy boat cruises, and savour fresh fish from the lake at our restaurant. A true Zambian paradise for nature lovers and weekend getaways.',
    location: 'Siavonga',
    address: '1 Lake Shore Drive, Siavonga, Zambia',
    phone: '+260 966 567 890',
    price: 520,
    priceUnit: 'night',
    latitude: -16.5315,
    longitude: 28.7062,
    images: JSON.stringify(['/lodges/lake-kariba-inn.jpg']),
    amenities: JSON.stringify(['WiFi', 'Pool', 'Breakfast', 'Parking', 'Restaurant', 'Bar']),
    rating: 4.6,
    totalRooms: 8,
  },
  {
    id: 'lodge-chipata-gateway',
    name: 'Chipata Gateway Lodge',
    description: 'Your gateway to Eastern Zambia and the spectacular South Luangwa National Park. Comfortable rooms with traditional Zambian decor, home-cooked meals using local ingredients, and a friendly staff ready to help you plan your safari adventure.',
    location: 'Chipata',
    address: '34 Mpezeni Way, Chipata, Zambia',
    phone: '+260 977 678 901',
    price: 300,
    priceUnit: 'night',
    latitude: -13.6327,
    longitude: 32.6478,
    images: JSON.stringify(['/lodges/chipata-gateway-lodge.jpg']),
    amenities: JSON.stringify(['WiFi', 'Breakfast', 'Parking', 'Restaurant']),
    rating: 4.2,
    totalRooms: 8,
  },
  {
    id: 'lodge-lusaka-premier',
    name: 'Lusaka Premier Lodge',
    description: 'The premier choice for discerning travellers in Lusaka. Elegantly furnished rooms with premium amenities, rooftop pool, fine dining restaurant, and a fully equipped business centre. Located in the prestigious Rhodespark area, minutes from Arcades Shopping Mall.',
    location: 'Lusaka',
    address: '56 Great East Road, Lusaka, Zambia',
    phone: '+260 955 789 012',
    price: 650,
    priceUnit: 'night',
    latitude: -15.4030,
    longitude: 28.3250,
    images: JSON.stringify(['/lodges/lusaka-premier-lodge.jpg']),
    amenities: JSON.stringify(['WiFi', 'Pool', 'Breakfast', 'Parking', 'AC', 'Restaurant', 'Bar']),
    rating: 4.8,
    totalRooms: 10,
  },
  {
    id: 'lodge-mosi-cultural-village',
    name: 'Mosi Cultural Village Lodge',
    description: 'An authentic cultural experience in Livingstone. Stay in traditionally-inspired chalets while enjoying modern comforts. Learn about the Toka-Leya people, watch traditional dance performances, and visit our craft village. Victoria Falls is just a short drive away.',
    location: 'Livingstone',
    address: '15 Mukuni Park Road, Livingstone, Zambia',
    phone: '+260 966 890 123',
    price: 380,
    priceUnit: 'night',
    latitude: -17.8392,
    longitude: 25.8615,
    images: JSON.stringify(['/lodges/mosi-cultural-village-lodge.jpg']),
    amenities: JSON.stringify(['WiFi', 'Breakfast', 'Parking', 'Restaurant', 'Bar']),
    rating: 4.4,
    totalRooms: 6,
  },
  {
    id: 'lodge-kitwe-business-park',
    name: 'Kitwe Business Park Lodge',
    description: 'Sleek, modern accommodation designed for the business traveller. Located in the Parklands business district with easy access to Kitwe\'s corporate offices. Self-catering options available, plus a café, gym, and secure parking.',
    location: 'Kitwe',
    address: '78 Parklands Road, Kitwe, Zambia',
    phone: '+260 955 901 234',
    price: 320,
    priceUnit: 'night',
    latitude: -12.8160,
    longitude: 28.2240,
    images: JSON.stringify(['/lodges/kitwe-business-park.jpg']),
    amenities: JSON.stringify(['WiFi', 'Breakfast', 'Parking', 'AC', 'Restaurant']),
    rating: 4.1,
    totalRooms: 12,
  },
  {
    id: 'lodge-ndola-comfort-inn',
    name: 'Ndola Comfort Inn',
    description: 'A cosy, family-friendly lodge offering warm hospitality at affordable prices. Clean, comfortable rooms with satellite TV, a lovely garden area, and a breakfast buffet that will fuel your day. Conveniently located near Ndola\'s main attractions.',
    location: 'Ndola',
    address: '9 Kansanshi Road, Ndola, Zambia',
    phone: '+260 977 012 345',
    price: 280,
    priceUnit: 'night',
    latitude: -12.9620,
    longitude: 28.6420,
    images: JSON.stringify(['/lodges/ndola-comfort-inn.jpg']),
    amenities: JSON.stringify(['WiFi', 'Breakfast', 'Parking', 'AC']),
    rating: 4.0,
    totalRooms: 10,
  },
  {
    id: 'lodge-siavonga-beach-resort',
    name: 'Siavonga Beach Resort',
    description: 'The ultimate lakeside getaway on Lake Kariba. Private beach access, water sports, beach bar, and sunset cruises. Our resort-style rooms offer panoramic lake views, and our chef prepares the finest fresh-from-the-lake cuisine. Perfect for honeymoons and celebrations.',
    location: 'Siavonga',
    address: '3 Lakeshore Boulevard, Siavonga, Zambia',
    phone: '+260 966 123 456',
    price: 720,
    priceUnit: 'night',
    latitude: -16.5380,
    longitude: 28.7100,
    images: JSON.stringify(['/lodges/siavonga-beach-resort.jpg']),
    amenities: JSON.stringify(['WiFi', 'Pool', 'Breakfast', 'Parking', 'AC', 'Restaurant', 'Bar']),
    rating: 4.7,
    totalRooms: 8,
  },
  {
    id: 'lodge-eastern-valley',
    name: 'Eastern Valley Lodge',
    description: 'Nestled in the scenic valley landscape of Eastern Province, this charming lodge offers a tranquil retreat from city life. Surrounded by rolling hills and traditional villages, it is the perfect base for exploring the Lessen Game Reserve and local markets.',
    location: 'Chipata',
    address: '67 Lundazi Road, Chipata, Zambia',
    phone: '+260 977 234 567',
    price: 250,
    priceUnit: 'night',
    latitude: -13.6400,
    longitude: 32.6600,
    images: JSON.stringify(['/lodges/eastern-valley-lodge.jpg']),
    amenities: JSON.stringify(['WiFi', 'Breakfast', 'Parking', 'Restaurant']),
    rating: 4.3,
    totalRooms: 7,
  },
]

async function main() {
  console.log('Seeding database with Zambian lodges...')

  for (const lodge of lodges) {
    await db.lodge.upsert({
      where: { id: lodge.id },
      update: lodge,
      create: lodge,
    })
    console.log(`  ✓ ${lodge.name}`)
  }

  console.log(`\nDone! Seeded ${lodges.length} lodges.`)
}

main()
  .catch((e) => {
    console.error('Seed error:', e)
    process.exit(1)
  })
  .finally(async () => {
    await db.$disconnect()
  })
